name = "Additive"
author = "SkywardMC"
version = "1.43.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "426a0da0831fbd616219212fe3a0ae555f0ea45bfe950bbf22bb214ad49f4167"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
