name = "Additive"
author = "SkywardMC"
version = "1.43.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0457e2c0ccd6fc5f056108db59c013eacba36b6083e4c1f744b02c29a21b23a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
