name = "Additive"
author = "SkywardMC"
version = "1.43.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4797f9918bda73a0c6a2f1799c9957c3fe936a6084e52f2d07a4a1b75cd0f6a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
